# Display constant
TITLE = "Chess"
TILES_NB = 8
TILE_SIZE = 98
WINDOW_WIDTH  = TILES_NB * TILE_SIZE
WINDOW_HEIGHT = TILES_NB * TILE_SIZE
TILE_WHITE_COLOR   = (235, 236, 208)
TILE_BLACK_COLOR   = (115, 149, 82)
TILE_SELECTED_WHITE_COLOR = (245, 246, 130)
TILE_SELECTED_BLACK_COLOR = (185, 202, 67)
TILE_CHECK_WHITE_COLOR = (224, 111, 103)
TILE_CHECK_BLACK_COLOR = (209, 65, 54)
POSSIBLE_MOVES_COLOR  = (92, 89, 87, 120)
PIECE_FILENAME = "pieces.png"
PIECE_IMAGE_NB_ROWS = 2
PIECE_IMAGE_NB_COL = 6
PIECE_IMAGE_WHITE_ROW = 0
PIECE_IMAGE_BLACK_ROW = 1
KING = 0
QUEEN = 1
BISHOP = 2
KNIGHT = 3
ROOK = 4
PAWN = 5
OFFSET1 = -3
OFFSET2 = 1
SCALING_W = 575
SCALING_H = 200

# Game constant
LINE_MOVE = [(1, 0), (-1, 0), (0, 1), (0, -1)]
DIAG_MOVE = [(1, 1), (-1, 1), (-1, -1), (1, -1)]
L_MOVE = [( 1,  2), ( 2,  1),
          (-1,  2), (-2,  1),
          (-1, -2), (-2, -1),
          ( 1, -2), ( 2, -1)]
SIDE_MOVE = [(-1, 0), (1, 0)]
WHITE = "white"
BLACK = "black"
PAWN_WHITE_MOVE = [(0,  1)]
PAWN_WHITE_CAPTURE_MOVE = [(1, 1), (-1, 1)]
PAWN_BLACK_MOVE = [(0, -1)]
PAWN_BLACK_CAPTURE_MOVE = [(1, -1), (-1, -1)]
KING_WHITE_STARTING_POS = (4, 0)
KING_BLACK_STARTING_POS = (4, 7)

PIECE_WHITE_ROW = 0
PIECE_BLACK_ROW = 7
ROOK_KINGSIDE_COL = 7
ROOK_QUEENSIDE_COL = 0
CASTLE_KINGSIDE_CHECK_COL = [5, 6]
CASTLE_QUEENSIDE_CHECK_COL = [1, 2, 3]
KING_CASTLE_KINGSIDE_COL = 6
KING_CASTLE_QUEENSIDE_COL = 2
ROOK_CASTLE_KINGSIDE_COL = 5
ROOK_CASTLE_QUEENSIDE_COL = 3
POS_WHITE_KING_KINGSIDE_CASTLE = (KING_CASTLE_KINGSIDE_COL, PIECE_WHITE_ROW)
POS_WHITE_KING_QUEENSIDE_CASTLE = (KING_CASTLE_QUEENSIDE_COL, PIECE_WHITE_ROW)
POS_BLACK_KING_KINGSIDE_CASTLE = (KING_CASTLE_KINGSIDE_COL, PIECE_BLACK_ROW)
POS_BLACK_KING_QUEENSIDE_CASTLE = (KING_CASTLE_QUEENSIDE_COL, PIECE_BLACK_ROW)
POS_WHITE_KING_CASTLE = [POS_WHITE_KING_KINGSIDE_CASTLE, POS_WHITE_KING_QUEENSIDE_CASTLE]
POS_BLACK_KING_CASTLE = [POS_BLACK_KING_KINGSIDE_CASTLE, POS_BLACK_KING_QUEENSIDE_CASTLE]
